import Navbar from "../components/Navbar";

export const metadata = {
  title: "RSBC AGENTS MANAGEMENT",
  description: "Generated by create next app",
};

export default function FormLayout({ children }) {
  return <div className="drawer-content">{children}</div>;
}
