import Faq from "./components/Faq";
import Navbar from "./components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "RSBC AGENTS MANAGEMENT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <div
          className="drawer drawer-end demo-wrap"
          // style={{
          //   backgroundImage:
          //     "url(https://img.freepik.com/free-photo/top-view-finance-business-elements_23-2148793757.jpg?w=900&t=st=1696823687~exp=1696824287~hmac=06ae9a0e49a87d6b3460e69d0d97bad005ed330378367dd62bbedb4cc8161aaa)",
          //   backgroundRepeat: "no-repeat",
          //   objectFit: "cover",
          //   backgroundSize: "100%",
          //   height: "100vh",
          // }}
        >
          <div className="demo-content">
            <input id="my-drawer" type="checkbox" className="drawer-toggle" />

            <div className="drawer-content">
              <Navbar />
              {children}
            </div>

            <div className="drawer-side overflow-hidden">
              <label htmlFor="my-drawer" className="drawer-overlay"></label>

              <ul className="menu p-4 w-96 min-h-full bg-base-200 text-base-content ">
                <div className="h-56 border-b-green-600 border-b-2">
                  TOP AGENTS
                </div>
                {/* <!-- Sidebar content here --> */}
                <ul className="menu w-full rounded-box">
                  <p className="menu-title">Frequently Ask questions</p>
                  <Faq />
                </ul>

                <label
                  htmlFor="my-drawer"
                  className="btn btn-primary drawer-button absolute top-3 right-3"
                >
                  Close
                </label>
              </ul>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
